name: badmintoon
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.1.0+1
  auto_size_text: ^3.0.0
  collection: ^1.19.1
  confetti: ^0.8.0
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  gap: ^3.0.1
  get_it: ^8.1.0
  google_fonts: ^6.3.0
  hexcolor: ^3.0.1
  hydrated_bloc: ^10.1.1
  image_downloader_web: ^2.0.7
  json_annotation: ^4.9.0
  toastification: ^3.0.3
  freezed_annotation: ^3.1.0
  uuid: ^4.5.1
  screenshot: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^10.1.0
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  flutter_gen_runner: ^5.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
